server:
  port: 8082
  servlet:
    context-path: /notification

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: notification-service
      port: 27017
      host: localhost
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

brevo:
  api-key: {BREVO_API_KEY}
  template-id: 2
