server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity-service}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  duration: 1 #hour

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

open:
  api:
    title: API Documents
    version: v1.0.0
    description: APIs docs for Green Shop website
    serverUrl: ${API_SERVER_URL:http://localhost:8080}
    serverDescription: local
