server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true