server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8484/realms/mini-blog-realm
        registration:
          keycloak:
            provider: keycloak
            client-id: mini-blog-gateway
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
            client-authentication-method: none
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8484/realms/mini-blog-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true