server:
  port: 8083
  servlet:
    context-path: /post

spring:
  application:
    name: post-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8484/realms/mini-blog-realm/protocol/openid-connect/certs
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: post-service
      port: 27017
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000ms
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      profileServiceCB:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3000ms

services:
  profile:
    url: http://localhost:8081/profile

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true