server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8484/realms/mini-blog-realm/protocol/openid-connect/certs
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: profileservice

grpc:
  server:
    port: 9091

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    metadata-map:
      grpc-port: ${grpc.server.port:9091}
      gRPC: ${grpc.server.port:9091}

