server:
  port: 8084
  servlet:
    context-path: /chat

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: chat-service
      port: 27017
      host: localhost
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
